#!/bin/sh
set -eu

prefix=/usr
exec_prefix=/usr
datarootdir=/usr/share
. "${datarootdir}/grub/grub-mkconfig_lib"

device="$(grub-probe --target=device /)"
uuid="$(grub-probe --target=fs_uuid /)"
access="$(prepare_grub_to_access_device "${device}" | sed 's/^/    /')"

cat <<EOF
menuentry 'Ming OS Legacy Root' --id 'ming-legacy' {
${access}
    linux /vmlinuz root=UUID=${uuid} ro ming.slot=legacy
    initrd /initrd.img
}
menuentry 'Ming OS Slot A' --id 'ming-slot-a' {
${access}
    linux /vmlinuz root=UUID=${uuid} ro ming.slot=A
    initrd /initrd.img
}
menuentry 'Ming OS Slot B' --id 'ming-slot-b' {
${access}
    linux /vmlinuz root=UUID=${uuid} ro ming.slot=B
    initrd /initrd.img
}
menuentry 'Ming OS Recovery (previous committed root)' --id 'ming-recovery-manual' {
${access}
    linux /vmlinuz root=UUID=${uuid} ro ming.slot=legacy ming.recovery=manual
    initrd /initrd.img
}
EOF
