[package]
name = "ming-tea-desktop"
version = "0.1.0"
description = "铭荼 desktop shell"
authors = ["Ming OS"]
edition = "2021"

[lib]
name = "ming_tea_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.4.1", features = [] }

[dependencies]
tauri = { version = "2.8.5", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
